const os = require('os');
const fs = require('fs');
const path = require('path');
const { writeEnvFile } = require('../src/cli/env-file');

let projectDir;

beforeEach(() => {
  projectDir = path.join(os.tmpdir(), `forge-envfile-test-${Date.now()}`);
  fs.mkdirSync(projectDir);
});

afterEach(() => {
  fs.rmSync(projectDir, { recursive: true, force: true });
});

function readEnvFile(filename = '.env.forge') {
  return fs.readFileSync(path.join(projectDir, filename), 'utf8');
}

test('writes service env vars using names from config', () => {
  writeEnvFile(projectDir, '.env.forge', {
    services: { mongo: 'mongodb://localhost:27017/sai' },
  }, {
    services: { mongo: { env: 'DATABASE_URL' } },
  });
  expect(readEnvFile()).toContain('DATABASE_URL=mongodb://localhost:27017/sai');
});

test('writes redis prefix env var when prefix and prefixEnv are set', () => {
  writeEnvFile(projectDir, '.env.forge', {
    services: { redis: 'redis://localhost:6379/1' },
  }, {
    services: { redis: { env: 'REDIS_URL', prefix: 'sai', prefixEnv: 'REDIS_KEY_PREFIX' } },
  });
  const content = readEnvFile();
  expect(content).toContain('REDIS_URL=redis://localhost:6379/1');
  expect(content).toContain('REDIS_KEY_PREFIX=sai');
});

test('skips redis prefix when prefix is not set', () => {
  writeEnvFile(projectDir, '.env.forge', {
    services: { redis: 'redis://localhost:6379/1' },
  }, {
    services: { redis: { env: 'REDIS_URL' } },
  });
  const content = readEnvFile();
  expect(content).toContain('REDIS_URL=redis://localhost:6379/1');
  expect(content).not.toContain('REDIS_KEY_PREFIX');
});

test('skips service with no env key configured', () => {
  writeEnvFile(projectDir, '.env.forge', {
    services: { mongo: 'mongodb://localhost:27017/sai' },
  }, {
    services: { mongo: {} }, // no env key
  });
  const content = readEnvFile();
  expect(content).toBe('# generated by forge — do not edit\n');
});

test('writes to custom envFile path', () => {
  writeEnvFile(projectDir, '.env.local', {
    services: { mongo: 'mongodb://localhost/sai' },
  }, {
    services: { mongo: { env: 'DB' } },
  });
  expect(fs.existsSync(path.join(projectDir, '.env.local'))).toBe(true);
  expect(fs.existsSync(path.join(projectDir, '.env.forge'))).toBe(false);
});

test('skips file write when envFile is false', () => {
  writeEnvFile(projectDir, false, {
    services: { mongo: 'mongodb://localhost/sai' },
  }, {
    services: { mongo: { env: 'DB' } },
  });
  expect(fs.existsSync(path.join(projectDir, '.env.forge'))).toBe(false);
});

test('overwrites existing file completely', () => {
  fs.writeFileSync(path.join(projectDir, '.env.forge'), 'OLD_VAR=old_value\n');
  writeEnvFile(projectDir, '.env.forge', { services: {} }, { services: {} });
  expect(readEnvFile()).toBe('# generated by forge — do not edit\n');
  expect(readEnvFile()).not.toContain('OLD_VAR');
});

test('includes generated-by header comment', () => {
  writeEnvFile(projectDir, '.env.forge', { services: {} }, { services: {} });
  expect(readEnvFile()).toMatch(/^# generated by forge — do not edit/);
});
