const fs = require('fs');
const path = require('path');

/**
 * Writes resolved service connection strings to the project's env file.
 * Per-process port values (portEnv) are NOT written here — they are injected
 * directly into each spawned process's environment at forge-up time (Plan 3).
 *
 * @param {string} projectPath  Absolute path to project root
 * @param {string|false} envFilename  Relative filename, or false to skip
 * @param {object} allocations  { ports: {}, services: { name: url } }
 * @param {object} config  The project's .forge/config.json content
 */
function writeEnvFile(projectPath, envFilename, allocations, config) {
  if (envFilename === false) return;

  const lines = ['# generated by forge — do not edit'];

  for (const [service, url] of Object.entries(allocations.services ?? {})) {
    const svcCfg = config.services?.[service] ?? {};
    if (svcCfg.env) lines.push(`${svcCfg.env}=${url}`);
    if (service === 'redis' && svcCfg.prefix && svcCfg.prefixEnv) {
      lines.push(`${svcCfg.prefixEnv}=${svcCfg.prefix}`);
    }
  }

  fs.writeFileSync(path.join(projectPath, envFilename), lines.join('\n') + '\n');
}

function ensureGitignored(projectPath, envFilename) {
  if (!envFilename) return 'no-file';
  const gitignorePath = path.join(projectPath, '.gitignore');
  if (!fs.existsSync(gitignorePath)) return 'no-gitignore';
  const content = fs.readFileSync(gitignorePath, 'utf8');
  if (content.split('\n').map(l => l.trim()).includes(envFilename)) return 'already';
  const appended = content.endsWith('\n') ? content + envFilename + '\n' : content + '\n' + envFilename + '\n';
  fs.writeFileSync(gitignorePath, appended);
  return 'added';
}

module.exports = { writeEnvFile, ensureGitignored };
