// test/e2e/add-flow.test.js
const os = require('os');
const fs = require('fs');
const path = require('path');
const http = require('http');
const { createServer } = require('../../src/daemon/server');
const { createRegistry } = require('../../src/daemon/registry');
const { createPortAllocator } = require('../../src/daemon/port-allocator');
const { createServiceManager } = require('../../src/daemon/services/manager');
const { writeEnvFile } = require('../../src/cli/env-file');
const { findFreePort } = require('../helpers/find-free-port');

let httpServer;
let daemonPort;
let registryPath;
let projectDir;
let registry;
let allocatedPort;

beforeAll(async () => {
  const candidatePort = await findFreePort();

  registryPath = path.join(os.tmpdir(), `forge-e2e-${Date.now()}.json`);
  projectDir = path.join(os.tmpdir(), `forge-e2e-proj-${Date.now()}`);
  fs.mkdirSync(path.join(projectDir, '.forge'), { recursive: true });

  fs.writeFileSync(
    path.join(projectDir, '.forge', 'config.json'),
    JSON.stringify({
      name: 'e2e-sai',
      envFile: '.env.forge',
      processes: [
        { name: 'api', command: 'echo hi', cwd: '.', ports: [candidatePort], portEnv: 'PORT' },
      ],
      services: {},
    })
  );

  registry = createRegistry(registryPath);
  // Empty service manager — no drivers, safe for unit/e2e tests without Docker
  const serviceManager = createServiceManager([]);
  const { app } = createServer({ registry, portAllocator: createPortAllocator(), serviceManager });
  httpServer = http.createServer(app);
  await new Promise(resolve => httpServer.listen(0, '127.0.0.1', resolve));
  daemonPort = httpServer.address().port;
});

afterAll(async () => {
  await new Promise(resolve => httpServer.close(resolve));
  fs.rmSync(projectDir, { recursive: true, force: true });
  if (fs.existsSync(registryPath)) fs.unlinkSync(registryPath);
});

test('register a project and receive port allocation', async () => {
  const config = JSON.parse(
    fs.readFileSync(path.join(projectDir, '.forge', 'config.json'), 'utf8')
  );
  const res = await fetch(`http://127.0.0.1:${daemonPort}/api/projects/register`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ ...config, path: projectDir }),
  });
  const body = await res.json();
  expect(res.status).toBe(200);
  expect(body.ok).toBe(true);
  expect(typeof body.allocations.ports.api).toBe('number');
  allocatedPort = body.allocations.ports.api;
});

test('project is persisted in registry after registration', () => {
  const project = registry.get('e2e-sai');
  expect(project).not.toBeNull();
  expect(project.path).toBe(projectDir);
  expect(project.allocations.ports.api).toBe(allocatedPort);
});

test('writeEnvFile produces correct output for the registered project', () => {
  const config = JSON.parse(
    fs.readFileSync(path.join(projectDir, '.forge', 'config.json'), 'utf8')
  );
  const project = registry.get('e2e-sai');
  // Simulate what forge add does after registration
  writeEnvFile(projectDir, config.envFile, project.allocations, config);

  const envContent = fs.readFileSync(path.join(projectDir, '.env.forge'), 'utf8');
  expect(envContent).toContain('# generated by forge — do not edit');
  // No service vars yet (services come in Plan 2), but file must be written
  expect(fs.existsSync(path.join(projectDir, '.env.forge'))).toBe(true);
});

test('second registration returns 409', async () => {
  const config = JSON.parse(
    fs.readFileSync(path.join(projectDir, '.forge', 'config.json'), 'utf8')
  );
  const res = await fetch(`http://127.0.0.1:${daemonPort}/api/projects/register`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ ...config, path: projectDir }),
  });
  expect(res.status).toBe(409);
});

test('delete project removes it from registry', async () => {
  const del = await fetch(`http://127.0.0.1:${daemonPort}/api/projects/e2e-sai`, {
    method: 'DELETE',
  });
  expect(del.status).toBe(200);
  expect(registry.get('e2e-sai')).toBeNull();
});
